//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISCity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsMark
    {
        public int id { get; set; }
        public int userRequest_id { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual UserRequests UserRequests { get; set; }
    }
}
