//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISCity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRequests()
        {
            this.RequestsMark = new HashSet<RequestsMark>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int mangeCompany_id { get; set; }
        public Nullable<int> subCompany_id { get; set; }
        public string Message { get; set; }
        public System.DateTime DateOfCreate { get; set; }
        public bool Closed { get; set; }
    
        public virtual ManageCompany ManageCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestsMark> RequestsMark { get; set; }
        public virtual SubCompany SubCompany { get; set; }
        public virtual Users Users { get; set; }
    }
}
